[package]
name = "Inbe"
entry = "src/main.zi"
module_roots = ["src"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"

[dependencies.kss]
git = "https://github.com/kryonlabs/kss.git"
ref = "master"

[dependencies.oqs]
git = "https://github.com/ziranlang/oqs.git"
ref = "master"

[dependencies.game2d]
git = "https://github.com/kryonlabs/game2d.git"
ref = "master"

[dependencies.daochi_client]
git = "https://github.com/ziranlang/daochi-client.git"
ref = "master"

[dependencies.sqlite]
git = "https://github.com/sqlite/sqlite.git"
ref = "master"
source = true

[dependencies.curl]
git = "https://github.com/curl/curl.git"
ref = "master"
source = true

[dependencies.liboqs]
git = "https://github.com/open-quantum-safe/liboqs.git"
ref = "main"
source = true

[dependencies.monocypher]
git = "https://github.com/LoupVaillant/Monocypher.git"
ref = "master"
source = true

[dependencies.rini]
git = "https://github.com/raysan5/rini.git"
ref = "main"
source = true
