# Inbe owns its account and transport dependencies. Kryon supplies UI only.
CMAKE ?= cmake

KRYON_LIBOQS_DIR := build/packages/liboqs
KRYON_LIBOQS_BUILD_DIR := $(KRYON_VENDOR_BUILD_DIR)/inbe-liboqs
KRYON_LIBOQS_A := $(KRYON_LIBOQS_BUILD_DIR)/lib/liboqs.a
KRYON_LIBOQS_INCLUDE := -I$(KRYON_LIBOQS_BUILD_DIR)/include
KRYON_LIBOQS_BUILD_TYPE ?= MinSizeRel
KRYON_LIBOQS_MINIMAL_BUILD ?= SIG_ml_dsa_44

KRYON_CURL_DIR := build/packages/curl
KRYON_CURL_BUILD_DIR := $(KRYON_VENDOR_BUILD_DIR)/inbe-curl
ifeq ($(NATIVE_PLATFORM),freebsd)
KRYON_CURL_INSTALL_LIBDIR := lib
else
KRYON_CURL_INSTALL_LIBDIR := lib64
endif
KRYON_CURL_INCLUDE_DIR := $(KRYON_CURL_BUILD_DIR)/include
KRYON_CURL_LIB_DIR := $(KRYON_CURL_BUILD_DIR)/$(KRYON_CURL_INSTALL_LIBDIR)
KRYON_CURL_A := $(KRYON_CURL_LIB_DIR)/libcurl.a
KRYON_CURL_SO := $(KRYON_CURL_A)
KRYON_CURL_PROTOCOL_CHECK := $(KRYON_CURL_BUILD_DIR)/.protocols-ok
KRYON_CURL_BUILD_TYPE ?= MinSizeRel
KRYON_CURL_CFLAGS := -DCURL_STATICLIB -I$(KRYON_CURL_INCLUDE_DIR)
KRYON_CURL_LDLIBS := $(KRYON_CURL_A) -lssl -lcrypto -lz -lpthread

$(KRYON_LIBOQS_A): $(KRYON_LIBOQS_DIR)/CMakeLists.txt
	$(CMAKE) -S $(KRYON_LIBOQS_DIR) -B $(KRYON_LIBOQS_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_LIBOQS_BUILD_TYPE) \
		-DBUILD_SHARED_LIBS=OFF -DOQS_BUILD_ONLY_LIB=ON \
		-DOQS_USE_OPENSSL=OFF -DOQS_DIST_BUILD=OFF \
		-DOQS_OPT_TARGET=generic \
		$(KRYON_LIBOQS_CPU_FEATURE_CMAKE_FLAGS) \
		-DOQS_MINIMAL_BUILD=$(KRYON_LIBOQS_MINIMAL_BUILD)
	$(CMAKE) --build $(KRYON_LIBOQS_BUILD_DIR) --target oqs

$(KRYON_CURL_A): $(KRYON_CURL_DIR)/CMakeLists.txt
	$(CMAKE) -S $(KRYON_CURL_DIR) -B $(KRYON_CURL_BUILD_DIR) \
		-DCMAKE_BUILD_TYPE=$(KRYON_CURL_BUILD_TYPE) \
		-DCMAKE_INSTALL_PREFIX=$(abspath $(KRYON_CURL_BUILD_DIR)) \
		-DCMAKE_INSTALL_LIBDIR=$(KRYON_CURL_INSTALL_LIBDIR) \
		-DBUILD_CURL_EXE=OFF -DBUILD_SHARED_LIBS=OFF \
		-DBUILD_STATIC_LIBS=ON -DCURL_USE_OPENSSL=ON \
		-DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF \
		-DCURL_USE_GSSAPI=OFF -DUSE_NGHTTP2=OFF \
		-DUSE_LIBIDN2=OFF -DCURL_DISABLE_LDAP=ON \
		-DCURL_DISABLE_LDAPS=ON -DCURL_DISABLE_SMB=ON \
		-DENABLE_CURL_MANUAL=OFF -DBUILD_EXAMPLES=OFF \
		-DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF \
		-DBUILD_TESTING=OFF $(KRYON_CURL_EXTRA_CMAKE_FLAGS)
	$(CMAKE) --build $(KRYON_CURL_BUILD_DIR) --target libcurl_static
	$(CMAKE) --build $(KRYON_CURL_BUILD_DIR) --target install

$(KRYON_CURL_PROTOCOL_CHECK): $(KRYON_CURL_A)
	@sh $(KRYON_CURL_BUILD_DIR)/curl-config --protocols | \
		grep -Eq '(^|[[:space:]])WS([[:space:]]|$$)'
	@sh $(KRYON_CURL_BUILD_DIR)/curl-config --protocols | \
		grep -Eq '(^|[[:space:]])WSS([[:space:]]|$$)'
	@touch $@
