#ifndef UI_ICON_TYPES_H
#define UI_ICON_TYPES_H

typedef enum {
    UI_ICON_TYPE_NONE,

    // Core UI icons
    UI_ICON_TYPE_GEAR,
    UI_ICON_TYPE_X,
    UI_ICON_TYPE_X_RED,
    UI_ICON_TYPE_MANUAL,
    UI_ICON_TYPE_RETURN,
    UI_ICON_TYPE_BACKWARD,
    UI_ICON_TYPE_FORWARD,
    UI_ICON_TYPE_PLAY,
    UI_ICON_TYPE_PAUSE,
    UI_ICON_TYPE_STAT,
    UI_ICON_TYPE_HOME,
    UI_ICON_TYPE_TRASH,
    UI_ICON_TYPE_PENCIL,
    UI_ICON_TYPE_SAVE,
    UI_ICON_TYPE_WRENCH,
    UI_ICON_TYPE_PLUS,
    UI_ICON_TYPE_STACK,
    UI_ICON_TYPE_CALENDAR,

    // Social & payment icons
    UI_ICON_TYPE_DISCORD,
    UI_ICON_TYPE_TELEGRAM,
    UI_ICON_TYPE_GITHUB,
    UI_ICON_TYPE_GLOBE,
    UI_ICON_TYPE_STRIPE,
    UI_ICON_TYPE_BTC,
    UI_ICON_TYPE_MONERO,

    // Sound icons
    UI_ICON_TYPE_SOUND,
    UI_ICON_TYPE_SOUND0,
    UI_ICON_TYPE_SOUND1,
    UI_ICON_TYPE_SOUND2,
    UI_ICON_TYPE_SOUND3,
    UI_ICON_TYPE_MUTE,
    UI_ICON_TYPE_MUSIC,

    // Habit & practice icons
    UI_ICON_TYPE_HABIT,
    UI_ICON_TYPE_AMEN,
    UI_ICON_TYPE_WEEKLY,
    UI_ICON_TYPE_INBE,

    // Meditation & theme icons
    UI_ICON_TYPE_DROID,
    UI_ICON_TYPE_FDROID,
    UI_ICON_TYPE_LIGHTON,
    UI_ICON_TYPE_LIGHTOFF,
    UI_ICON_TYPE_MOON,
    UI_ICON_TYPE_SUN,
    UI_ICON_TYPE_JUPITER,
    UI_ICON_TYPE_MARS,
    UI_ICON_TYPE_MERCURY,
    UI_ICON_TYPE_VENUS,
    UI_ICON_TYPE_SATURN,

    // Navigation & utility icons
    UI_ICON_TYPE_LINK,
    UI_ICON_TYPE_EDIT,
    UI_ICON_TYPE_EYE_CLOSED,
    UI_ICON_TYPE_CHECK,
    UI_ICON_TYPE_QUEST,
    UI_ICON_TYPE_ROUTINE,
    UI_ICON_TYPE_TIMELINE,
    UI_ICON_TYPE_TODOS,
    UI_ICON_TYPE_TILE,
    UI_ICON_TYPE_TILE2,
    UI_ICON_TYPE_TILE3,
    UI_ICON_TYPE_TILE4,
    UI_ICON_TYPE_TEXT,

    // Platform & store icons
    UI_ICON_TYPE_ITCH,
    UI_ICON_TYPE_PLAYSTORE,
    UI_ICON_TYPE_TUX,
    UI_ICON_TYPE_WIN,
    UI_ICON_TYPE_UXN,
    UI_ICON_TYPE_WASM,
    UI_ICON_TYPE_WASM4,
    UI_ICON_TYPE_RAY,
    UI_ICON_TYPE_ROCKET,
    UI_ICON_TYPE_SRHT,
    UI_ICON_TYPE_TCL,

    UI_ICON_TYPE_COUNT
} UIIconType;

#endif
