#!/bin/sh
set -eu

icon_dir=${1:-icons}
out=${2:-src/flint_icon_assets.c}
tmp="${out}.tmp"

icon_files=$(find "$icon_dir" -maxdepth 1 -type f -name '*.png' | LC_ALL=C sort)

icon_ident()
{
    printf '%s' "$1" | sed 's/[^A-Za-z0-9]/_/g'
}

icon_enum()
{
    icon_ident "$1" | tr '[:lower:]' '[:upper:]'
}

{
    printf '/* Generated by scripts/embed-icons.sh. */\n'
    printf '#include "flint_icons.h"\n\n'

    for file in $icon_files; do
        name=$(basename "$file" .png)
        ident=$(icon_ident "$name")

        printf 'static const unsigned char flint_icon_%s[] = {\n' "$ident"
        od -An -v -tx1 "$file" | awk '
        {
            printf "   ";
            for(i = 1; i <= NF; i++)
                printf " 0x%s,", $i;
            printf "\n";
        }'
        printf '};\n\n'
    done

    printf 'const FlintIconAsset flint_icon_assets[] = {\n'
    count=0
    for file in $icon_files; do
        name=$(basename "$file" .png)
        ident=$(icon_ident "$name")
        enum=$(icon_enum "$name")
        size=$(wc -c < "$file" | tr -d ' ')
        printf '    {FLINT_ICON_TYPE_%s, "%s", flint_icon_%s, %su},\n' "$enum" "$name" "$ident" "$size"
        count=$((count + 1))
    done
    printf '};\n\n'
    printf 'const unsigned int flint_icon_asset_count = %su;\n' "$count"
} > "$tmp"

mv "$tmp" "$out"
