#!/bin/sh
set -eu

out=${1:-src/flint_embedded_asset_data.c}
shift || true

tmp="${out}.tmp"

asset_files=""
for path in "$@"; do
    if [ -f "$path" ]; then
        asset_files="${asset_files}
$path"
    elif [ -d "$path" ]; then
        found=$(find "$path" -type f | LC_ALL=C sort)
        if [ -n "$found" ]; then
            asset_files="${asset_files}
$found"
        fi
    fi
done

asset_files=$(printf '%s\n' "$asset_files" | sed '/^$/d' | LC_ALL=C sort -u)

asset_ident()
{
    printf '%s' "$1" | sed 's#^\./##; s#[^A-Za-z0-9]#_#g'
}

asset_path()
{
    printf '%s' "$1" | sed 's#^\./##; s#^/##'
}

asset_mime()
{
    case "$1" in
        *.png) printf 'image/png' ;;
        *.jpg|*.jpeg) printf 'image/jpeg' ;;
        *.ogg) printf 'audio/ogg' ;;
        *.ini|*.txt|*.dat) printf 'text/plain' ;;
        *) printf 'application/octet-stream' ;;
    esac
}

{
    printf '/* Generated by scripts/embed-assets.sh. */\n'
    printf '#include "flint_embedded_assets.h"\n\n'

    index=0
    for file in $asset_files; do
        ident=$(asset_ident "$file")
        printf 'static const unsigned char flint_embedded_asset_%s_%u[] = {\n' "$ident" "$index"
        od -An -v -tx1 "$file" | awk '
        {
            printf "   ";
            for(i = 1; i <= NF; i++)
                printf " 0x%s,", $i;
            printf "\n";
        }'
        printf '};\n\n'
        index=$((index + 1))
    done

    printf 'const FlintEmbeddedAsset flint_embedded_assets[] = {\n'
    index=0
    count=0
    for file in $asset_files; do
        ident=$(asset_ident "$file")
        path=$(asset_path "$file")
        mime=$(asset_mime "$file")
        size=$(wc -c < "$file" | tr -d ' ')
        printf '    {"%s", "%s", flint_embedded_asset_%s_%u, %su},\n' "$path" "$mime" "$ident" "$index" "$size"
        index=$((index + 1))
        count=$((count + 1))
    done
    printf '};\n\n'
    printf 'const unsigned int flint_embedded_asset_count = %su;\n' "$count"
} > "$tmp"

mv "$tmp" "$out"
