#ifndef INBE_META_H
#define INBE_META_H

#define INBE_TITLE "Inner Breeze"
#define INBE_WIDTH 240
#define INBE_HEIGHT 320

// Theme colors - Blue theme
#define INBE_BACKGROUND_R 226
#define INBE_BACKGROUND_G 238
#define INBE_BACKGROUND_B 252
#define INBE_BACKGROUND_A 255

#define INBE_BUTTON_R 166
#define INBE_BUTTON_G 207
#define INBE_BUTTON_B 242
#define INBE_BUTTON_A 255

#define INBE_BUTTON_HOVER_R 104
#define INBE_BUTTON_HOVER_G 158
#define INBE_BUTTON_HOVER_B 215
#define INBE_BUTTON_HOVER_A 255

#define INBE_CIRCLE_R 126
#define INBE_CIRCLE_G 183
#define INBE_CIRCLE_B 230
#define INBE_CIRCLE_A 255

#define INBE_TEXT_R 36
#define INBE_TEXT_G 72
#define INBE_TEXT_B 124
#define INBE_TEXT_A 255

#endif
