#ifndef APP_DESKTOP_TRAY_H
#define APP_DESKTOP_TRAY_H

#include "app_fwd.h"

typedef enum DesktopTrayAction {
    DESKTOP_TRAY_ACTION_NONE = 0,
    DESKTOP_TRAY_ACTION_SHOW,
    DESKTOP_TRAY_ACTION_HIDE,
    DESKTOP_TRAY_ACTION_MINIMIZE,
    DESKTOP_TRAY_ACTION_CLOSE_REQUEST,
    DESKTOP_TRAY_ACTION_START_WHM,
    DESKTOP_TRAY_ACTION_START_MEDITATION,
    DESKTOP_TRAY_ACTION_START_SUN_SALUTATION,
    DESKTOP_TRAY_ACTION_START_PATTERNS,
    DESKTOP_TRAY_ACTION_QUIT,
    DESKTOP_TRAY_ACTION_MARK_HABIT_0,
    DESKTOP_TRAY_ACTION_MARK_HABIT_1,
    DESKTOP_TRAY_ACTION_MARK_HABIT_2,
    DESKTOP_TRAY_ACTION_MARK_HABIT_3,
    DESKTOP_TRAY_ACTION_MARK_HABIT_4,
    DESKTOP_TRAY_ACTION_MARK_HABIT_5,
    DESKTOP_TRAY_ACTION_MARK_HABIT_6,
    DESKTOP_TRAY_ACTION_MARK_HABIT_7,
    DESKTOP_TRAY_ACTION_MARK_HABIT_8,
    DESKTOP_TRAY_ACTION_MARK_HABIT_9,
    DESKTOP_TRAY_ACTION_BREAK_REST_NOW,
    DESKTOP_TRAY_ACTION_BREAK_MODE_NORMAL,
    DESKTOP_TRAY_ACTION_BREAK_MODE_QUIET,
    DESKTOP_TRAY_ACTION_BREAK_MODE_SUSPENDED,
    DESKTOP_TRAY_ACTION_BREAK_READING_TOGGLE,
    DESKTOP_TRAY_ACTION_BREAK_SETTINGS
} DesktopTrayAction;

int desktop_tray_init(void);
int desktop_tray_ready(void);
void desktop_tray_shutdown(void);
DesktopTrayAction desktop_tray_poll_action(void);
void desktop_tray_apply_action(InnerBreeze*app, DesktopTrayAction action, int *quit);
void desktop_tray_update_status(InnerBreeze*app);
void desktop_tray_keep_running(void);

#endif
